version: '3.8'

services:
  hue:
    image: gethue/hue
    ports:
      - "8888:8888"
    volumes:
      - ./conf/hue.ini:/usr/share/hue/desktop/conf/hue.ini
    container_name: hue
    hostname: hue     

  hive:
    image: apache/hive:4.0.0
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./data:/data
      - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    environment:
      - SERVICE_NAME=hiveserver2
    container_name: hive
    hostname: hive    
    restart: unless-stopped